name: Simple CI Pipeline

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ci-demo-main

      - name: Run ESLint
        run: npx eslint .
        working-directory: ci-demo-main
      
      - name: Run a basic test
        run: echo "CI Pipeline Running!"
        
      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pytest

      - name: Run tests
        run: bash test_script.sh

      - name: Run unit tests
        run: pytest test.py
