name: Security Scan
on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Trivy
      run: |
        sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/download/v0.59.1/trivy_0.59.1_Linux-64bit.tar.gz
        tar -zxvf trivy_0.59.1_Linux-64bit.tar.gz
        sudo mv trivy /usr/local/bin/

    - name: Scan Docker image for vulnerabilities
      run: |
        trivy fs . > trivy_report.txt
        if grep -q "CRITICAL\|HIGH" trivy_report.txt; then
          echo "Vulnerabilities found! Failing the workflow."
          exit 1
        else
          echo "No critical or high vulnerabilities found."
        fi
